name: foodhub
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  material_design_icons_flutter: ^5.0.6595
  firebase_core: ^2.32.0

  image_picker: ^1.0.7
  animations: ^2.0.11
  animated_glitch: ^2.0.0+2
  carousel_slider: ^4.2.1
  google_nav_bar: ^5.0.6
  flutter_screenutil: ^5.9.0
  another_flutter_splash_screen: ^1.2.0
  lottie: ^3.1.0
  animated_text_kit: ^4.2.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.4
  flutter_native_splash: ^2.3.10
  intl: ^0.19.0
  dio: ^5.4.1

  cached_network_image: ^3.3.1
  audioplayers: ^6.0.0
  bloc: ^8.1.3
  blurrycontainer: ^1.0.2
  curved_navigation_bar: ^1.0.3
  animated_bottom_navigation_bar: ^1.3.3
  flutter_spinkit: ^5.2.1
  responsive_framework: ^0.1.4
  firebase_auth: ^4.20.0
  flutter_advanced_drawer: ^1.3.6
  hidden_drawer_menu: ^3.0.1
  http: ^1.2.1
  shimmer: ^3.0.0
  flutter_gradient_text: ^1.0.1
  flutter_staggered_grid_view: ^0.4.0
  shared_preferences: ^2.2.3
  flutter_animate: ^4.5.0
  go_router: ^14.2.1
  flexify: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_native_splash:
  color: "#000000"
  image: "assets/music_app.png"
  android: true
  ios: true
flutter_icons:
  android: true
  ios: true
  image_path: "assets/music_app.png"
  adaptive_icon_background: "#191919"

min_sdk_android: 21

flutter_lints:
riverpod_generator:
build_runner:
custom_lint:
riverpod_lint:

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Phosphate
      fonts:
        - asset: assets/fonts/Phosphate Font/Phosphate.ttf
    - family: Sofia Pro
      fonts:
        - asset: assets/fonts/Sofia Pro Regular Az.otf
        - asset: assets/fonts/Sofia Pro Medium Az.otf
